# Generated by Django 5.2.7 on 2025-10-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='github_profile',
            field=models.URLField(blank=True, max_length=300, verbose_name='Профіль GitHub'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступний для роботи'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin_profile',
            field=models.URLField(blank=True, max_length=300, verbose_name='Профіль LinkedIn'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=300, verbose_name='Місце проживання'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефону'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, max_length=300, verbose_name='Вебсайт'),
        ),
    ]
